# Generated by Django 3.1 on 2020-08-24 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_content', models.CharField(max_length=255)),
                ('evaluation_nate', models.CharField(max_length=120)),
                ('remind_note', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LongTermPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_end_date', models.DateField(null=True)),
                ('longterm_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myplan.longtermplan')),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermProcessEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myplan.evaluation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myplan.shorttermplan')),
            ],
        ),
        migrations.AddField(
            model_name='shorttermplan',
            name='process_evaluation',
            field=models.ManyToManyField(through='myplan.ShortTermProcessEvaluation', to='myplan.Evaluation'),
        ),
        migrations.AddField(
            model_name='shorttermplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlanForDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(null=True)),
                ('finished', models.BooleanField(default=False)),
                ('in_date', models.DateField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myplan.shorttermplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_planning_reminder', models.BooleanField(default=True)),
                ('daily_activity_review_reminder', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LongTermProcessEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myplan.evaluation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myplan.longtermplan')),
            ],
        ),
        migrations.AddField(
            model_name='longtermplan',
            name='process_evaluation',
            field=models.ManyToManyField(through='myplan.LongTermProcessEvaluation', to='myplan.Evaluation'),
        ),
        migrations.AddField(
            model_name='longtermplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('time', models.DateTimeField()),
                ('event_note', models.CharField(max_length=255)),
                ('important_level', models.CharField(choices=[('NI', 'NotImportant'), ('I', 'Important'), ('VI', 'VeryImportant')], default='NI', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationForDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myplan.evaluation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
