# Generated by Django 3.1 on 2020-08-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='evaluation_nate',
            new_name='evaluation_note',
        ),
    ]
