# Generated by Django 3.1 on 2020-08-24 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myplan', '0002_auto_20200824_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planforday',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myplan.shorttermplan'),
        ),
        migrations.AlterField(
            model_name='shorttermplan',
            name='longterm_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myplan.longtermplan'),
        ),
    ]
